#!/usr/bin/env python

import argparse
import beagledaq
from time import sleep
from math import sin, pi

parser = argparse.ArgumentParser(description='Output a sinusoid on DAC0')
parser.add_argument('-c', '--channels', type=int, choices=range(8),
                    action='append', help='Channel(s) to output on')
parser.add_argument('amplitude', metavar='amp', type=float,
                    help='Value from 0 to 32767')
parser.add_argument('frequency', metavar='freq', type=float,
                    help='Value in Hz')

bd = beagledaq.beagle_daq()

args = parser.parse_args()
amp = args.amplitude
freq = args.frequency
channels = [0] if args.channels == None else args.channels
t = 0
while True:
    data = int(0x7fff + amp*sin(2*pi*(t*1e-3)*freq))
    for channel in channels:
        bd.write(channel, data)
    sleep(1e-3)
    t += 1
